---
name: CI to Docker hub

on:
  push:
    # Only publish Docker image only on semver tag.
    tags:
      - "v*.*.*"

  # # Run lint, build and test jobs for any PRs.
  # pull_request:

env:
  DOCKER_IMAGE: "mvignjevic/bats-with-helpers"

jobs:
  lint:
    name: Run linters against test_helpers.bash and Dockerfile
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository under $GITHUB_WORKSPACE, so workflow can access it.
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run linters
        run: make lint

  test_build:
    name: Build Docker image and exercise tests from test-example.bats
    # Ensure lint job passes before building image and testing.
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Docker meta to get semver version
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # List of Docker images to use as base name for tags
          images: ${DOCKER_IMAGE}
          tag-semver: "{{version}}"

      - name: Build image using the latest tag
        run: make build VERSION=${{ steps.docker_meta.outputs.version }}

      - name: Run test-example.bats unit tests against previously built Docker image
        run: make test VERSION=${{ steps.docker_meta.outputs.version }}
